### ISSUE TITLE
Receiving a large commitNumber in ChangeEventHeader causes an error

### ISSUE THREAD

**Issue by pozil** [developerforce/pub-sub-api#44]
This issue was initially raised [here in the JS client repo](https://github.com/pozil/pub-sub-api-node-client/issues/21) but I believe that it affects all clients as it seems to be related to the schema definition:

A large `commitNumber` value under `ChangeEventHeader` can exceed the allocated Avro type buffer space and cause an error. For example `1698100138468892700` does not fit in the expected `Long` type and this causes issues with Avro when deserializing. 

As I stated in the original issue, I don't think that this can be fixed on the client side. Can we ensure that the Avro schema supports all possible values for this field?

**Comment by branburciaga** [comment]
Following as my team is who reported the issue to pozil in the JS client repo. This is super urgent for us as it's completely broken our Pub Sub implementation and we no longer get updates, causing our systems to be out of sync.

**Comment by ashiemke** [comment]
This issue seems to be causing other issues and the message appears to be corrupted (avro-js throws a "truncated buffer" exception when trying to read a string later in the message, misreading the length to be several MB in ~hundreds of bytes of message).

I can provide the message and schema, but don't want to post it publicly since I can't decode to verify it doesn't contain sensitive information.

**Comment by pozil** [comment]
Closing this as this was an avro-js specific bug that prevents us from properly unserializing the event payload.
Long story short: the JS library doesn't support all the values that fit in a 64 bit Long. It's limited to the values that fit a JS Number (2^53 – 1). Fortunately, we can overcome this limitation with a custom deserializer for the Avro Long type.
